ci02:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "40000:50000"
    - "8060:8080"
  volumes:
    - /var/lib/jenkins:/var/jenkins_home
  labels:
    - "traefik.frontend.rule=Host:localhost.ci02.morotai.de, ci02.morotai.de"
    - "- traefik.frontend.passHostHeader=true"
