master:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /var/jenkins_home
  labels:
    - "traefik.frontend.rule=Host:localhost.ci01.morotai.de, ci01.morotai.de"
    - "- traefik.frontend.passHostHeader=true"
