version: "3.2"
services:
  ci02:
    build: .
    user: root
    restart: always
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "40000:50000"
      - "8060:8080"
    volumes:
        - type: mount
          source: /var/lib/jenkins/ci02
          target: /var/jenkins_home
        - type: mount
          source: /var/run/docker.sock
          target: /var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:localhost.ci02.morotai.de, ci02.morotai.de"
      - "- traefik.frontend.passHostHeader=true"

volumes:
  jenkins_home:
  docker:
