version: "3.2"
services:
  ci03:
    build: .
    user: root
    restart: always
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "30000:50000"
      - "8050:8080"
    volumes:
        - type: bind
          source: /var/lib/jenkins/ci03
          target: /var/jenkins_home
    labels:
      - "traefik.frontend.rule=Host:localhost.ci03.morotai.de, ci03.morotai.de"
      - "- traefik.frontend.passHostHeader=true"
